### ISSUE TITLE
Error: Device timeout

### ISSUE THREAD

**Issue by jonferreira** [stephenkeep/node-red-contrib-chromecast#2]
It seems that a timeout makes node-red crash and restart, I reckon this shouldn't be happening!

```
 6 Nov 17:40:50 - [red] Uncaught Exception:
 6 Nov 17:40:51 - Error: Device timeout
 at HeartbeatController.ontimeout (/home/pi/.node-red/node_modules/node-red-contrib-chromecast/node_modules/castv2-client/lib/senders/platform.js:56:26)
 at HeartbeatController.g (events.js:260:16)
 at emitNone (events.js:67:13)
 at HeartbeatController.emit (events.js:166:7)
 at ontimeout [as _onTimeout] (/home/pi/.node-red/node_modules/node-red-contrib-chromecast/node_modules/castv2-client/lib/controllers/heartbeat.js:44:10)
 at Timer.listOnTimeout (timers.js:92:15)
 Welcome to Node-RED
 ===================
 6 Nov 17:40:54 - [info] Node-RED version: v0.13.3
 6 Nov 17:40:54 - [info] Node.js  version: v4.4.7
 6 Nov 17:40:54 - [info] Linux 4.1.18-v7+ arm LE
 6 Nov 17:40:54 - [info] Loading palette nodes
 6 Nov 17:41:07 - [info] Settings file
```

**Comment by mini1368** [comment]
same problem, fresh installation, only hacs und node red installed
